# Generated by Django 5.2.8 on 2025-12-02 05:52

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ImageAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="uploads/")),
                ("detections", models.JSONField()),
                ("processing_time_ms", models.IntegerField(blank=True, null=True)),
                ("image_width", models.IntegerField(blank=True, null=True)),
                ("image_height", models.IntegerField(blank=True, null=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("class_name", models.CharField(blank=True, max_length=100, null=True)),
                ("confidence", models.FloatField(blank=True, null=True)),
                ("quality", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "embedding",
                    pgvector.django.vector.VectorField(
                        blank=True, dimensions=512, null=True
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
                "indexes": [
                    models.Index(
                        fields=["class_name"], name="ml_layer_im_class_n_917621_idx"
                    ),
                    models.Index(
                        fields=["uploaded_at"], name="ml_layer_im_uploade_594492_idx"
                    ),
                ],
            },
        ),
    ]
