# Generated by Django 5.2.8 on 2025-12-02 06:05

from django.db import migrations
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        VectorExtension(),
    ]

    run_before = [
        ("ml_layer", "0001_initial"),
    ]
