# Generated by Django 5.2.8 on 2025-12-03 10:10

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ml_layer", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SeedImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="uploads/")),
                ("detections", models.JSONField()),
                ("processing_time_ms", models.IntegerField(blank=True, null=True)),
                ("image_width", models.IntegerField(blank=True, null=True)),
                ("image_height", models.IntegerField(blank=True, null=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("prediction", models.CharField(blank=True, max_length=100, null=True)),
                ("confidence", models.FloatField(blank=True, null=True)),
                ("quality", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "embedding",
                    pgvector.django.vector.VectorField(
                        blank=True, dimensions=512, null=True
                    ),
                ),
                (
                    "blockchain_tx_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.DeleteModel(
            name="ImageAnalysis",
        ),
        migrations.AddIndex(
            model_name="seedimage",
            index=models.Index(
                fields=["prediction"], name="ml_layer_se_predict_fa0daa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="seedimage",
            index=models.Index(
                fields=["uploaded_at"], name="ml_layer_se_uploade_e8be32_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="seedimage",
            index=models.Index(
                fields=["blockchain_tx_id"], name="ml_layer_se_blockch_8f429e_idx"
            ),
        ),
    ]
