# Generated by Django 5.2.8 on 2025-12-09 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ml_layer", "0002_seedimage_delete_imageanalysis_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="seedimage",
            name="blockchain_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("fabric", "Fabric"),
                    ("sawtooth", "Sawtooth"),
                    ("unknown", "Unknown"),
                ],
                default="unknown",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="seedimage",
            index=models.Index(
                fields=["blockchain_type"], name="ml_layer_se_blockch_61596f_idx"
            ),
        ),
    ]
