# Generated by Django 5.2.8 on 2025-12-16 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ml_layer", "0003_seedimage_blockchain_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="seedimage",
            name="signer_name",
            field=models.CharField(
                blank=True, default="Unknown", max_length=100, null=True
            ),
        ),
    ]
