# Generated by Django 5.2.8 on 2025-12-19 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ml_layer", "0004_seedimage_signer_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="seedimage",
            name="bbox",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="seedimage",
            name="original_image_path",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
